### ISSUE TITLE
La méthode `getSpanSizeForPosition` de la classe `SmartRecyclerAdapter` peut provoquer un crash

### ISSUE THREAD

**Issue by ludovicroland** [smartnsoft/smartrecyclerview-android#1]
Chemin de reproduction :

1. Créer une liste avec implémentation du DiffUtil avec un seul élément dedans
2. Appeler la méthode `setWrappersForDiffUtil` du `DiffUtilSmartRecyclerAdapter` avec en paramètre une liste vide
3. Constater le crash

La stacktrace :

```
 java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
at java.util.ArrayList.get(ArrayList.java:439)
at com.smartnsoft.recyclerview.adapter.SmartRecyclerAdapter.getSpanSizeForPosition(SmartRecyclerAdapter.java:301)
at com.landicta.wellogy.fragment.ListFragment$getLayoutManager$1.getSpanSize(ListFragment.kt:38)
at com.landicta.wellogy.wrapper.DefaultGridItemDecoration.computeSpaceElementDimension(DefaultGridItemDecoration.kt:32)
at com.landicta.wellogy.wrapper.DefaultGridItemDecoration.getItemOffsets(DefaultGridItemDecoration.kt:19)
at android.support.v7.widget.RecyclerView.getItemDecorInsetsForChild(RecyclerView.java:4792)
at android.support.v7.widget.RecyclerView$LayoutManager.calculateItemDecorationsForChild(RecyclerView.java:9320)
at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:590)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
 at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3763)
at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3527)
at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1767)
at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:356)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
at android.view.Choreographer.doCallbacks(Choreographer.java:723)
at android.view.Choreographer.doFrame(Choreographer.java:655)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
at android.os.Handler.handleCallback(Handler.java:790)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6494)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Le problème, dans ce cas prévis vient du fait que la méthode `getSpanSizeForPosition(int)` est appelé avec une position à `-1`.  Comme la condition `if (position < wrappers.size())` est remplie, l'application crash sur la ligne suivante :

```
return wrappers.get(position).getSpanSize();
```

Il convient donc de vérifier si, en plus, la position est bien supérieure ou égale à 0.

**Comment by ludovicroland** [comment]
Resolved in the version 1.5.1
